version: 2
updates:

# GitHub actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

# npm
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/list/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/mongodb-backup/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/mongodb-restore/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/postgresql-backup/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/postgresql-restore/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /apps/prune/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /packages/commands/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /packages/mongodb-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /packages/postgresql-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /packages/storage-service-clients/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: /packages/storage-service-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only

# Docker
- package-ecosystem: docker
  directory: /.devcontainer/
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /docker/
  schedule:
    interval: daily
