version: 2
updates:

# GitHub actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
  ignore:
  # See: https://github.com/bakunyo/git-pr-release-action/issues/15, https://github.com/samunohito/SimpleVolumeMixer/commit/2059044c71236509466cf9b1bb2d56d515274938
  - dependency-name: bakunyo/git-pr-release-action

# npm
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/list/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/mongodb-backup/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/mongodb-restore/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/postgresql-backup/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/postgresql-restore/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /apps/prune/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /packages/commands/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /packages/mongodb-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /packages/postgresql-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /packages/storage-service-clients/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: npm
  directory: /packages/storage-service-test/
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope

# Docker
- package-ecosystem: docker
  directory: /.devcontainer/
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
- package-ecosystem: docker
  directory: /docker/
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
