categories:
- title: 'BREAKING CHANGES'
  labels:
  - 'breaking'
- title: '💎 Features'
  labels:
  - 'feature'
- title: '🚀 Improvement'
  labels:
  - 'improvement'
- title: '🐛 Bug Fixes'
  labels:
  - 'bug'
- title: '🧰 Maintenance'
  labels:
  - 'support'
  - 'dependencies'
category-template: '### $TITLE'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
- label: 'feature'
  branch:
  - '/^feat\/.+/'
- label: 'improvement'
  branch:
  - '/^imprv\/.+/'
- label: 'bug'
  branch:
  - '/^fix\/.+/'
  title:
  - '/^fix/i'
- label: 'support'
  branch:
  - '/^support\/.+/'
  title:
  - '/^support/i'
  - '/^chore/i'
  - '/^ci/i'
  - '/^docs/i'
  - '/^test/i'
include-labels:
- breaking
- feature
- improvement
- bug
- support
- dependencies
exclude-labels:
- 'exclude from changelog'
template: |
  $CHANGES
