name: Misc - Command - Bump up version

on:
  issue_comment:
    types: [created, edited]

jobs:

  bump-version:
    runs-on: ubuntu-latest

    if: >
      contains( github.event.comment.html_url, '/pull/' )
      && startsWith( github.event.comment.body, '/bump-version ' )

    steps:
    - name: Map certain command from comment
      run: |
        COMMAND=$(echo ${{ github.event.comment.body }} | sed -e 's/\/bump-version [[:space:]]*\(.*\)/\1/')
        bash -c "[[ ${COMMAND} =~ (patch|minor|major) ]]"
        exit $?

    - uses: actions/checkout@v3
    - name: Bump up version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        yarn run "bump-version:$COMMAND"

        git commit -am 'Bump up version'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
