name: Misc - Command - Bump up version

on:
  issue_comment:
    types: [created, edited]

jobs:

  bump-version:
    runs-on: ubuntu-latest

    if: >
      contains( github.event.comment.html_url, '/pull/' )
      && startsWith( github.event.comment.body, '/bump-version ' )

    steps:
    - name: Map certain command from comment
      id: bump_version
      run: |
        UP_RANGE=$(echo ${{ github.event.comment.body }} | sed -e 's/\/bump-version [[:space:]]*\(.*\)/\1/')
        bash -c "[[ ${UP_RANGE} =~ (patch|minor|major) ]]"
        echo "::set-output name=up_range::${UP_RANGE}"

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "16.13.1"
        cache: "yarn"
    - run: yarn install
    - name: Bump up version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        yarn run "bump-version:${{ steps.bump_version.outputs.up_range }}"

        git commit -am 'Bump up version'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
