name: Release - Prepare next master

on:
  pull_request:
    types: [closed]
    branches:
    - stable

jobs:
  bump-up-version:
    if:  github.head_ref == 'master'

    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: master
      UPDATE: patch
      COMMIT_MESSAGE: "Bump up version"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: "16.13.1"
        cache: "yarn"
    - run: yarn install
    - name: Bump up version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout ${{ env.TARGET_BRANCH }} -b next-version

        yarn run bump-version:${{ env.UPDATE }}

        git commit -am '${{ env.COMMIT_MESSAGE }}'
        git push

        gh pr create --title "Prepare next version"
