name: Release - Make next PR

on:
  push:
    branches:
    - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Make next PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install
      - name: Run changeset version
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: yarn changeset version
