name: Application test

on:
  push:
    branches-ignore: [stable]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - name: Set and restore cache of Turborepo
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/turbo
          key: |
            turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-
      - run: yarn install
      - run: yarn test:ci
      # [TODO] Coverage report
