name: Application test

on:
  push:
    branches-ignore: [stable]

jobs:
  test:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Start all DBs and middle
      run: docker-compose -d -f .devcontainer/docker-compose.yml up
    # [TODO] use healthcheck to wait on
    - run: sleep 30
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -- node bash -c 'yarn install && yarn test'
    # [TODO] Coverage report
