name: Application test

on:
  push:
    branches-ignore: [stable]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir node_modules && sudo chown 1000:1000 node_modules
    - name: Start all DBs and middle
      run: docker-compose -f .devcontainer/docker-compose.yml up -d
    # [TODO] use healthcheck to wait on
    - run: sleep 30
    - run: docker-compose -f .devcontainer/docker-compose.yml exec -T -- node bash -c 'yarn install && yarn test'
    # [TODO] Coverage report
